version: '3.3'

services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  eureka:
   build: ./uengine5-eureka/
   restart: always
   ports:
     - "8761:8761"
   environment:
     SPRING_PROFILES_ACTIVE: compose

  zuul:
   depends_on:
     - uengine5-eureka
   build: ./uengine5-zuul/
   ports:
     - "8080:8080"
   restart: always
   environment:
     SPRING_PROFILES_ACTIVE: compose
     EUREKA_HOST: uengine5-eureka

  definition-service:
    depends_on:
      - uengine5-eureka
      - kafka
    build: ./definition-service/
    ports:
      - "9010:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: compose
      EUREKA_HOST: uengine5-eureka
      KAFKA_HOST: kafka
      DB_HOST: jdbc:mysql://bpm-dev.cxp0klyrcjfk.ap-northeast-2.rds.amazonaws.com
      DB_USER: root
      DB_PASS: 18925ung

  process-service:
    depends_on:
      - uengine5-eureka
      - kafka
    build: ./process-service/
    ports:
      - "9020:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: compose
      EUREKA_HOST: uengine5-eureka
      KAFKA_HOST: kafka
      DB_HOST: jdbc:mysql://bpm-dev.cxp0klyrcjfk.ap-northeast-2.rds.amazonaws.com
      DB_USER: root
      DB_PASS: 18925ung

