spring:
  application:
    name: zuul-router


server:
  port: 8080
  servletPath: /

zuul:
  addProxyHeaders: true

  routes:
    definition:
      path: /definition/**
      serviceId: definition
      stripPrefix: false
    version:
      path: /version/**
      serviceId: definition
      stripPrefix: false
    instance:
      path: /instance/**
      serviceId: bpm
      stripPrefix: false
    instance-entity:
      path: /instances/**
      serviceId: bpm
      stripPrefix: false
    instance-service:
      path: /service/**
      serviceId: bpm
      stripPrefix: false
    instance-services:
      path: /services/**
      serviceId: bpm
      stripPrefix: false
    worklist-entity:
      path: /worklist/**
      serviceId: bpm
      stripPrefix: false
    instance-workitem:
      path: /work-item/**
      serviceId: bpm
      stripPrefix: false
    metadata:
      path: /classdefinition/**
      serviceId: bpm
      stripPrefix: false


#### important for BPM introspection  ####

    eureka:
      path: /eureka/**
      url: ${eureka.client.serviceUrl.defaultZone}
      stripPrefix: true

    bpm:
      path: /bpm/**
      serviceId: bpm
      stripPrefix: true

###########################################

endpoints:
  routes:
    sensitive: false

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000
  ConnectTimeout: 10000
  ReadTimeout: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: ${eureka_url}
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health