---
server:
  port: 9010
  servlet:
    context-path: /

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bpm-dev.cxp0klyrcjfk.ap-northeast-2.rds.amazonaws.com:3306/iam
    username: root
    password: 18925ung

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    statusPageUrlPath: ${server.servlet.context-path}info
    healthCheckUrlPath: ${server.servlet.context-path}health
    metadataMap:
        deployment: local
        profile: local

kafka:
  bootstrap-servers: localhost:9092
  topic:
    bpm: bpm.topic
  consumer-topic: bpm

---
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles: compose
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/bpm
    username: ${DB_USER}
    password: ${DB_PASS}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    statusPageUrlPath: ${server.servlet.context-path}info
    healthCheckUrlPath: ${server.servlet.context-path}health
    metadataMap:
        deployment: local
        profile: local

kafka:
#    bootstrap-servers: cloud.pas-mini.io:10091
  bootstrap-servers: ${KAFKA_HOST}:9092
  topic:
    bpm: bpm.topic
  consumer-topic: bpm