spring:
  application:
    name: definition

server:
  port: 8090
  servletPath: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.47:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
