spring:
  application:
    name: bpm

server:
  port: 8090
  servletPath: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health

kafka:
  bootstrap-servers: localhost:9092
#  bootstrap-servers: cloud.pas-mini.io:10091
#  bootstrap-servers: localhost:10091
  topic:
    bpm: bpm.topic