---
spring:
  profiles: local

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000
    renewalPercentThreshold: 0.49
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: compose

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000
    renewalPercentThreshold: 0.49
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
